import os
import re

class YAMLEngine:
    @staticmethod
    def parse_simple_yaml(yaml_path):
        """Simple pure-Python YAML parser for key-value dictionary mappings."""
        data = {}
        current_section = "General"
        
        if not os.path.exists(yaml_path):
            return data

        with open(yaml_path, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith("#"):
                    continue
                if line.endswith(":"):
                    current_section = line[:-1].strip()
                    if current_section not in data:
                        data[current_section] = {}
                elif ":" in line:
                    key, val = line.split(":", 1)
                    key = key.strip()
                    val = val.strip().strip('"').strip("'")
                    if current_section not in data:
                        data[current_section] = {}
                    data[current_section][key] = val
        return data

    @staticmethod
    def inject_variables(yaml_data, context):
        """Replaces placeholders ($RENDERER, $INTERNAL_RES) with system variables."""
        processed = {}
        for section, keys in yaml_data.items():
            processed[section] = {}
            for k, v in keys.items():
                for ctx_k, ctx_v in context.items():
                    v = v.replace(f"${ctx_k.upper()}", str(ctx_v))
                processed[section][k] = v
        return processed

    @staticmethod
    def write_ini_config(target_ini_path, config_dict):
        """Injects or updates target INI file keys cleanly."""
        os.makedirs(os.path.dirname(target_ini_path), exist_ok=True)
        
        existing_lines = []
        if os.path.exists(target_ini_path):
            with open(target_ini_path, "r", encoding="utf-8") as f:
                existing_lines = f.readlines()

        # Write or update keys inside sections
        with open(target_ini_path, "w", encoding="utf-8") as f:
            f.write("# --- GENERATED BY EMULATORCONFIG-1CLICK ---\n")
            for section, keys in config_dict.items():
                f.write(f"[{section}]\n")
                for k, v in keys.items():
                    f.write(f"{k} = {v}\n")
                f.write("\n")
